/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.chat.e2e;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Soubhik
 */
public class ThemeSettingsPanel extends javax.swing.JPanel {

    private SettingsWindowDialog settingsFrameReference;

    /**
     * Creates new form ThemeSettingsPanel
     */
    public ThemeSettingsPanel(SettingsWindowDialog settingsFrame) {
        initComponents();
        settingsFrameReference = settingsFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        selectThemeLabel = new javax.swing.JLabel();
        selectThemeChooseBox = new javax.swing.JComboBox<>();

        selectThemeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectThemeLabel.setText("Select app theme:");
        selectThemeLabel.setToolTipText("");

        selectThemeChooseBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FlatLaf Light", "FlatLaf Dark", "FlatLaf IntelliJ", "FlatLaf Darcula", "Arc", "Arc - Orange", "Arc Dark", "Arc Dark - Orange", "Carbon", "Cobalt 2", "Cyan Light", "Dark Flat", "Dark Purple", "Dracula", "Gradianto Dark Fuchsia", "Gradianto Deep Ocean", "Gradianto Midnight Blue", "Gradianto Nature Green", "Gray", "Gruvbox Dark Hard", "Gruvbox Dark Medium", "Gruvbox Dark Soft", "Hiberbee Dark", "High contrast", "Light Flat", "Material Design Dark", "Monocai", "Monokai Pro", "Nord", "One Dark", "Solarized Dark", "Solarized Light", "Spacegray", "Vuesion", "Xcode-Dark", "Arc Dark (Material)", "Atom One Dark (Material)", "Atom One Light (Material)", "Dracula (Material)", "GitHub (Material)", "GitHub Dark (Material)", "Light Owl (Material)", "Material Darker (Material)", "Material Deep Ocean (Material)", "Material Lighter (Material)", "Material Oceanic (Material)", "Material Palenight (Material)", "Monokai Pro (Material)", "Moonlight (Material)", "Night Owl (Material)", "Solarized Dark (Material)", "Solarized Light (Material)" }));
        selectThemeChooseBox.setToolTipText("Theme changes instantly on selection");
        selectThemeChooseBox.setSelectedItem(ConfigManager.getCurrentTheme());
        selectThemeChooseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectThemeChooseBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(selectThemeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(selectThemeChooseBox, 0, 394, Short.MAX_VALUE))
                                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(selectThemeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectThemeChooseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>

    private void selectThemeChooseBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ConfigManager.setCurrentTheme((String)selectThemeChooseBox.getSelectedItem());
    }


    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> selectThemeChooseBox;
    private javax.swing.JLabel selectThemeLabel;
    // End of variables declaration

    public JComboBox<String> getSelectThemeChooseBox()
    {
        return selectThemeChooseBox;
    }
}
